### ISSUE TITLE
display errors as inline markup rather than tooltips

### ISSUE THREAD

**Issue by RpprRoger** [neontribe/cottage-booking#20]
so html

``` html
<div>
    <label for="username">Your username</label>
    <input class="errors" type="text" id="username" aria-describedby="username-tip" >
    <div role="tooltip" id="username-tip">There is an error</div>
</div>
```

``` css
:input.errors + [role="tooltip"] {
    display: none;
}
:input.errors:focus + [role="tooltip"] {
    display: block;
}
```
